FROM python:3.11-slim
RUN apt-get update && \
	apt-get install -y binutils nasm socat && \
	rm -rf /var/lib/apt/lists/*
COPY challenge/challenge.py /
EXPOSE 1337
CMD ["socat", "tcp-l:1337,reuseaddr,fork", "EXEC:./challenge.py"]