FROM haproxy:2.3-alpine

# Install packages
RUN echo "http://dl-cdn.alpinelinux.org/alpine/v3.9/main" >> /etc/apk/repositories
RUN echo "http://dl-cdn.alpinelinux.org/alpine/v3.9/community" >> /etc/apk/repositories
RUN apk add --update --no-cache supervisor nodejs npm openjdk17-jre mongodb gcc g++ cargo make libffi-dev openssl-dev build-base netcat-openbsd yaml-cpp

# Install curl
ENV CURL_VERSION=7.70.0
RUN wget https://curl.haxx.se/download/curl-${CURL_VERSION}.tar.gz && tar xfz curl-${CURL_VERSION}.tar.gz \
    && cd curl-${CURL_VERSION}/ && ./configure --with-ssl \
    && make -j 16 && make install

# Setup Neo4j
ENV NEO4J_VERSION=5.13.0
RUN curl https://dist.neo4j.org/neo4j-community-${NEO4J_VERSION}-unix.tar.gz -o neo4j-community-${NEO4J_VERSION}-unix.tar.gz
RUN tar zxf neo4j-community-${NEO4J_VERSION}-unix.tar.gz
RUN mv neo4j-community-${NEO4J_VERSION} /opt/
RUN ln -s /opt/neo4j-community-${NEO4J_VERSION} /opt/neo4j

# Copy flag
COPY flag.txt /flag.txt

# Setup app
RUN mkdir -p /app

# Add application
WORKDIR /app
COPY challenge .

# Install dependencies
RUN npm install
RUN npm rebuild

# Setup supervisord
COPY conf/supervisord.conf /etc/supervisord.conf

# Setup HAProxy
COPY conf/haproxy.conf /usr/local/etc/haproxy/haproxy.cfg

# Expose the port node-js is reachable on
EXPOSE 1337

# Populate database and start supervisord
COPY --chown=root entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
