FROM python:3.8-slim-buster 

RUN apt update && apt install -y socat ruby-full php-cli build-essential

# Add application
WORKDIR /challenge
COPY challenge .
RUN chmod a+w -R /challenge

# Expose the port
EXPOSE 1337

# Switch to use a non-root user from here on
USER nobody

# Start the python application
CMD ["socat", "-dd", "TCP-LISTEN:1337,reuseaddr,fork", "exec:python -u /challenge/server.py"]
