######################
#    SSH INSTANCE    #
######################
FROM debian:bookworm-slim as ssh-instance

RUN apt-get update -qqy && \
    apt-get install -qqy \
    zsh \
    git \
    sudo \
    curl \
    wget \
    openssh-server

ENV SSH_PORT=2222

RUN useradd -m satoshi
RUN echo satoshi:L4mb0Pr0j3ct | chpasswd

USER satoshi
RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
ENV ZSH=/home/satoshi/.oh-my-zsh
RUN sed -i -e "/source \$ZSH\/oh-my-zsh.sh/i export ZSH_COMPDUMP=\$ZSH\/cache\/.zcompdump-\$HOST" /home/satoshi/.zshrc
RUN rm -rf /home/satoshi/.zcompdump
RUN echo 'PROMPT="%{$fg[yellow]%}%n%{$fg[green]%}@%m%{$reset_color%} ${PROMPT}"' >> $ZSH/themes/robbyrussell.zsh-theme

USER root
RUN chsh -s $(which zsh) satoshi

RUN mkdir /var/run/sshd
RUN sed -i "s/#PermitRootLogin prohibit-password/PermitRootLogin no/" /etc/ssh/sshd_config
RUN sed -i "s/#PasswordAuthentication yes/PasswordAuthentication yes/" /etc/ssh/sshd_config
RUN sed -i "s/#Port [0-9]*/Port ${SSH_PORT}/" /etc/ssh/sshd_config

RUN chown -R satoshi:satoshi /home/satoshi


##########################
#    SERVERS & CONFIGS   #
##########################
FROM ssh-instance as servers

### bitcoin-25.0, electrs, electrs-server, chall handler ###
COPY ./servers/ /root/servers/

### copy config files ###
COPY ./configs/ /root/configs/
COPY ./configs/bitcoin.conf /root/.bitcoin/bitcoin.conf

### install python3 & necessary tools ###
RUN true \
    && wget -q https://download.electrum.org/4.4.6/Electrum-4.4.6.tar.gz \
    && apt update -qqy \
    && apt install -qqy \ 
        python3 \
        python3-pip \
        python3-pyqt5 \
        libsecp256k1-dev \
        python3-cryptography \
        librocksdb-dev \
        cargo \
        clang \
        cmake \
        jq \
    && rm -rf /usr/lib/python3.*/EXTERNALLY-MANAGED \
    && python3 -m pip install --user Electrum-4.4.6.tar.gz && rm -f Electrum-4.4.6.tar.gz \
    && rm -rf /var/cache/apt/archives/ \
    && true

### Electrum Rust Server ###
ENV ROCKSDB_INCLUDE_DIR=/usr/include
ENV ROCKSDB_LIB_DIR=/usr/lib
WORKDIR /root/servers/electrs/
RUN cargo install --locked --path .
RUN cp -uv /root/.cargo/bin/electrs /root/.local/bin/electrs


#############################
#     STARTUP & SCRIPTS     #
#############################
FROM servers as startup

RUN true \
    && mkdir -p /root/logs/chall/ \
    && apt update -qqy \
    && apt install -qqy xinetd tini \
    && rm -rf /var/cache/apt/archives/ \
    && true

COPY ./startup/ /root/startup/
COPY ./scripts/ /root/scripts/
RUN echo 'export PATH="/root/servers/bitcoin-25.0/bin:/root/.local/bin:$PATH"' >> /root/.bashrc

EXPOSE 50002
EXPOSE 8888
EXPOSE 2222

### Finalizing ###
FROM startup as final

WORKDIR /
ENTRYPOINT [ "/root/scripts/entrypoint.sh" ]
