FROM alpine:3.14.1
RUN addgroup -S www && adduser -S www -G www

# Install python/pip
ENV PYTHONUNBUFFERED=1
RUN apk add --update --no-cache python3 python3-dev && ln -sf python3 /usr/bin/python
RUN python3 -m ensurepip
RUN pip3 install --no-cache --upgrade pip setuptools

# Install packages
RUN apk add --no-cache --update mariadb nginx mariadb-client supervisor gcc musl-dev openssl mariadb-connector-c-dev nodejs npm uwsgi uwsgi-python3
RUN apk add --no-cache chromium chromium-chromedriver

# Upgrade pip
RUN python -m pip install --upgrade pip

# Setup files
RUN mkdir -p /app && mkdir -p /email && mkdir -p /bot
COPY challenge /app
COPY email-app /email
COPY bot /bot
RUN mkdir -p /app/application/contracts
# Setup Mailhog
RUN wget https://github.com/mailhog/MailHog/releases/download/v1.0.1/MailHog_linux_amd64
RUN chmod +x MailHog_linux_amd64

# Setup Bot
RUN addgroup -S bot && adduser -S bot -G bot
RUN chown -R bot:bot /bot

# Generate SSL certificates
RUN openssl genpkey -algorithm RSA -out /etc/ssl/private/nginx-selfsigned.key && openssl req -new -x509 -keyout /etc/ssl/private/nginx-selfsigned.key -out /etc/ssl/certs/nginx-selfsigned.crt -days 365 -nodes -subj "/C=US/ST=DemoState/L=DemoCity/O=DemoOrg/OU=DemoUnit/CN=localhost"

# Setup nginx temporary file
RUN mkdir /var/tmp/nginx
RUN chown www:www /var/tmp/nginx
RUN chown -R nginx:nginx /var/lib/nginx/tmp
RUN chmod -R 755 /var/lib/nginx/tmp

# Setup Email App
WORKDIR /email
RUN npm i

# Setup challenge
WORKDIR /app
RUN pip install -r requirements.txt

# Copy configs
COPY config/supervisord.conf /etc/supervisord.conf
COPY config/nginx.conf /etc/nginx/nginx.conf

# Expose port the server is reachable on
EXPOSE 1337

# Disable pycache
ENV PYTHONDONTWRITEBYTECODE=1

# Setup flag
COPY flag.txt /root/flag
RUN chmod 600 /root/flag

# Setup readflag
COPY config/readflag.c /
RUN gcc -o /readflag /readflag.c && chmod 4755 /readflag && rm /readflag.c

# create database and start supervisord
COPY --chown=root entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
