default:
ifdef name
	@cd challenge; \
		mkdir -p ../release/hardware_$(name); \
	 	cp -r ./fs ../release/hardware_$(name);

	@cd release; \
	 	zip -9 -r ./hardware_$(name).zip ./hardware_$(name); \
		unzip -l ./hardware_$(name).zip;
		
	@echo [+] Challenge was built successfully.
else
	@echo [-] Please define the challenge name. For example, \"make name=cool_chall_name\"
endif

test: clean default

clean:
	@rm -rf release/*
	@echo [+] Challenge release deleted successfully.
