#!/bin/bash

PYTHONUNBUFFERED=true gunicorn \
    --user ctf \
    --group ctf \
    --bind 0.0.0.0:$HTTP_PORT \
    --daemon \
    --workers 1 \
    --threads 1 \
    --access-logfile /var/log/ctf/gunicorn.access.log \
    --error-logfile /var/log/ctf/gunicorn.error.log \
    --capture-output \
    --log-level debug \
    eth_sandbox.server:app
