services:
  russian_roulette:
    container_name: russian_roulette
    build: .
    ports:
      - "1337:1337"
    networks:
      - shared_net
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 1337 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  shared_net:
    external: true
