FROM python:3.11-alpine

RUN apk update --no-cache && apk add --no-cache socat

WORKDIR /challenge
COPY challenge/main.py .
USER nobody

EXPOSE 1337

CMD ["socat", "-dd", "TCP-LISTEN:1337,reuseaddr,fork", "exec:python -u /challenge/main.py"]