FROM alpine:latest
ENV DEBIAN_FRONTEND noninteractive

RUN apk add --no-cache qemu-system-x86_64 socat

RUN addgroup -g 1000 ctf && adduser -u 1000 -G ctf -h /home/ctf -D ctf

ADD --chown=ctf challenge/* /home/ctf/

RUN chown -R root:ctf /home/ctf

RUN chmod 750 /home/ctf/run.sh
RUN chmod 777 /home/ctf/initramfs.cpio.gz
RUN chmod 750 /home/ctf/vmlinuz-linux

WORKDIR /home/ctf

EXPOSE 9001/tcp

ENTRYPOINT ["socat", "TCP-LISTEN:9001,fork", "EXEC:'/home/ctf/run.sh'"]