FROM debian:12-slim
RUN apt-get update && \
    apt-get install -y socat && \
    rm -rf /var/lib/apt/lists/*
ADD challenge/main /
ADD challenge/flag.txt /
EXPOSE 1337
ENTRYPOINT ["socat", "tcp-l:1337,reuseaddr,fork", "EXEC:./main"]
