# Name of PROG and CFLAGS shall be changed.

PROG = main
SRC = $(PROG).c
CFLAGS = -fno-stack-protector -no-pie -Wl,-z,relro,-z,now -w -Xlinker -rpath=./glibc/ -Xlinker -I./glibc/ld-linux-x86-64.so.2

all: compile 

compile:
	@echo "Compiling $(SRC) -> $(PROG)"
	gcc  $(SRC) -o pet_companion $(CFLAGS)

clean:
	rm -f $(PROG)


