FROM debian:buster-slim

# Install packages
RUN apt update -y; apt install -y rabbitmq-server supervisor curl 

# Enable rabbitmq web interface
RUN rabbitmq-plugins enable rabbitmq_management

# Expose rabbitmq web interface
EXPOSE 15672

# Create RabbitMQ config file
RUN echo "loopback_users.guest = false" > /etc/rabbitmq/rabbitmq.conf

# Copy rabbitmq initialisation script
COPY entrypoint.sh /entrypoint.sh

# Setup supervisor
COPY config/supervisord.conf /etc/supervisord.conf

# Run supervisord
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisord.conf"]