FROM python:3.11-alpine

# Disable pycache
ENV PYTHONDONTWRITEBYTECODE=1

# Upgrade pip
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir flask

# add ctf user
RUN addgroup -S ctf && adduser -S ctf -G ctf

# copy challenge files
COPY challenge/ /home/ctf/

WORKDIR /home/ctf
USER ctf

ENV FLASK_APP=main.py

EXPOSE 1337

CMD ["flask", "run", "--host=0.0.0.0", "--port=1337"]
