# Name of PROG and CFLAGS shall be changed.

PROG = writing_on_the_wall # CHANGE THIS
SRC = main.c
CFLAGS = -fstack-protector-all -Wl,-z,relro,-z,now -w -Xlinker -rpath=./glibc/ -Xlinker -I./glibc/ld-linux-x86-64.so.2

all: compile 

compile:
	@echo "Compiling $(SRC) -> $(PROG)"
	gcc  $(SRC) -o $(PROG) $(CFLAGS)

clean:
	rm -f $(PROG)


